### ISSUE TITLE
WorkStealingThreadpool - tree of tasks - unexpected behaviour

### ISSUE THREAD

**Issue by dev-depintel** [cpp-taskflow/cpp-taskflow#65] opened 2019-02-07 00:04 UTC
Hi,

I am observing some unexpected behaviour when trying to dynamically spawn a tree of tasks.

Here is a simple example: 

```C++
void syncLog(std::string const& msg)
{
    static std::mutex logMutex;
    std::lock_guard<std::mutex> lock(logMutex);
    std::cout << msg << '\n';
}

void grow(tf::SubflowBuilder& subflow, uint64_t depth)
{
    syncLog("Depth: " + std::to_string(depth));
    std::this_thread::sleep_for(std::chrono::seconds(1));
    if(depth < 3)
    {
        subflow.silent_emplace(
                [depth](tf::SubflowBuilder& subsubflow){grow(subsubflow, depth+1);},
                [depth](tf::SubflowBuilder& subsubflow){grow(subsubflow, depth+1);});
        subflow.detach();
    }
}

int main(int argc, char *argv[])
{
    tf::Taskflow mainTaskFlow(8);
    mainTaskFlow.silent_emplace([](tf::SubflowBuilder& subflow){grow(subflow, 0);});
    mainTaskFlow.wait_for_all();
}
```
Here is the dumped topology of the main taskflow: [here](https://imgur.com/3v6dXlD)

Using "WorkStealingThreadpool" I have the following (unexpected) output:

```text
[09:54:22] Depth: 0 
[09:54:23] Depth: 1
[09:54:24] Depth: 2
[09:54:25] Depth: 3 **Only a single thread running until here**
[09:54:26] Depth: 2 **Only two threads from here**
[09:54:26] Depth: 3 
[09:54:27] Depth: 3
[09:54:27] Depth: 1
[09:54:28] Depth: 3
[09:54:28] Depth: 2
[09:54:29] Depth: 3
[09:54:29] Depth: 2
[09:54:30] Depth: 3
[09:54:30] Depth: 3
[09:54:31] Depth: 3
```
Using "SimpleThreadpool"  I have the following (expected) output:
```text
[10:02:31] Depth: 0 *one thread*
[10:02:32] Depth: 1 *two threads*
[10:02:32] Depth: 1
[10:02:33] Depth: 2 *four threads*
[10:02:33] Depth: 2
[10:02:33] Depth: 2
[10:02:33] Depth: 2
[10:02:34] Depth: 3 *eight threads*
[10:02:34] Depth: 3
[10:02:34] Depth: 3
[10:02:34] Depth: 3
[10:02:34] Depth: 3
[10:02:34] Depth: 3
[10:02:34] Depth: 3
[10:02:34] Depth: 3
```

**Comment by twhuang-uiuc** [comment] 2019-02-08 16:35
Hi @dev-depintel  Thanks for bringing this up. Yes, I noticed this issue - not a bug. I am fixing it. Will keep you posted.

**Comment by twhuang-uiuc** [comment] 2019-02-15 04:59
Hi @dev-depintel , this problem is fixed now. Please update with the master branch. Thank you for bringing this up!

**Comment by dev-depintel** [comment] 2019-02-15 05:05
Hi @twhuang-uiuc, thanks, keep up the good work.

**Comment by twhuang-uiuc** [comment] 2019-02-15 05:10
@dev-depintel thanks! The newest `WorkStealingThreadpool` has improved the performance as well. Please play around with it.

**Closed** 2019-04-30 18:18 UTC
